server:
  servlet:
    context-path: /yto

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/yto
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    jedis:
      pool:
        max-wait: 3000
        max-idle: 300
        max-active: 100

mybatis:
  mapper-locations: mapper/*.xml
<<<<<<< HEAD
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
=======
  #打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



>>>>>>> 1011ff0 (新增订单查询分配)

